import { Timeframe } from "@/lib/market-data/types";

export type BreakoutState = "breakout" | "breakdown" | "inside-range";
export type OptionsDirectionalBias = "call" | "put" | "neutral";
export type OptionsStructureBias = "long_call" | "call_spread" | "long_put" | "put_spread" | "no_trade" | "watchlist";

export type FeatureSnapshot = {
  symbol: string;
  timeframe: Timeframe;
  asOf: string;
  latestOpen: number;
  latestHigh: number;
  latestLow: number;
  close: number;
  priorClose: number;
  dailyChangePercent: number;
  oneMonthChangePercent: number;
  threeMonthChangePercent: number;
  sixMonthChangePercent: number;
  oneYearChangePercent: number;
  barCount: number;
  sma20: number;
  sma50: number;
  sma200: number;
  distanceFrom20Sma: number;
  distanceFrom50Sma: number;
  distanceFrom200Sma: number;
  isAbove20: boolean;
  isAbove50: boolean;
  isAbove200: boolean;
  smaStackAligned: boolean;
  sma200SlopePercent: number;
  twentyDayHigh: number;
  twentyDayLow: number;
  fiftyTwoWeekHigh: number;
  fiftyTwoWeekLow: number;
  distanceFrom52WeekHigh: number;
  distanceFrom52WeekLow: number;
  breakoutState: BreakoutState;
  atr14: number;
  atrPercent: number;
  volumeVs20DayAverage: number;
  rangeCompressionRatio: number;
  averageDollarVolume20: number;
  realizedVol20: number;
  realizedVol60: number;
  closeLocationPercent: number;
  expectedMove5DayPercent: number;
  expectedMove10DayPercent: number;
  momentumComposite: number;
  trendComposite: number;
  bullishBreakoutScore: number;
  bearishBreakdownScore: number;
  premiumBuyingScore: number;
  directionalConvictionScore: number;
  optionsDirectionalBias: OptionsDirectionalBias;
  optionsStructureBias: OptionsStructureBias;
};
