import { UniverseTicker } from "@/lib/universe/types";

export const CORE_TECH_UNIVERSE: UniverseTicker[] = [
  { symbol: "NVDA", name: "NVIDIA", tier: "tier1", section: "tech", segment: "fabless", benchmarkLinks: ["SOXX", "SMH", "QQQ"], tags: ["semis", "ai", "gpu", "liquid-options"] },
  { symbol: "AMD", name: "Advanced Micro Devices", tier: "tier1", section: "tech", segment: "fabless", benchmarkLinks: ["SOXX", "SMH", "QQQ"], tags: ["semis", "cpu", "gpu", "liquid-options"] },
  { symbol: "AVGO", name: "Broadcom", tier: "tier1", section: "tech", segment: "networking", benchmarkLinks: ["SOXX", "SMH", "QQQ"], tags: ["semis", "datacenter", "liquid-options"] },
  { symbol: "TSM", name: "Taiwan Semiconductor", tier: "tier1", section: "tech", segment: "foundry", benchmarkLinks: ["SOXX", "SMH", "QQQ"], tags: ["semis", "foundry", "liquid-options"] },
  { symbol: "QCOM", name: "Qualcomm", tier: "tier1", section: "tech", segment: "fabless", benchmarkLinks: ["SOXX", "SMH", "QQQ"], tags: ["semis", "wireless", "liquid-options"] },
  { symbol: "MU", name: "Micron Technology", tier: "tier1", section: "tech", segment: "memory", benchmarkLinks: ["SOXX", "SMH"], tags: ["semis", "memory", "liquid-options"] },
  { symbol: "MRVL", name: "Marvell Technology", tier: "tier1", section: "tech", segment: "datacenter", benchmarkLinks: ["SOXX", "SMH", "QQQ"], tags: ["semis", "networking", "datacenter"] },
  { symbol: "ANET", name: "Arista Networks", tier: "tier1", section: "tech", segment: "datacenter", benchmarkLinks: ["QQQ", "SMH"], tags: ["networking", "datacenter", "ai-infra"] },
  { symbol: "VRT", name: "Vertiv Holdings", tier: "tier1", section: "tech", segment: "datacenter", benchmarkLinks: ["QQQ"], tags: ["cooling", "power", "datacenter"] },
  { symbol: "SMCI", name: "Super Micro Computer", tier: "tier1", section: "tech", segment: "datacenter", benchmarkLinks: ["QQQ"], tags: ["servers", "ai-infra", "hardware"] },
  { symbol: "CRWV", name: "CoreWeave", tier: "tier1", section: "tech", segment: "datacenter", benchmarkLinks: ["QQQ"], tags: ["cloud", "gpu", "ai-infra", "datacenter"] },
  { symbol: "ARM", name: "Arm Holdings", tier: "tier2", section: "tech", segment: "fabless", benchmarkLinks: ["SOXX", "QQQ"], tags: ["semis", "ip", "cpu"] },
  { symbol: "INTC", name: "Intel", tier: "tier2", section: "tech", segment: "foundry", benchmarkLinks: ["SOXX", "SMH", "QQQ"], tags: ["semis", "foundry", "cpu"] },
  { symbol: "AMAT", name: "Applied Materials", tier: "tier2", section: "tech", segment: "equipment", benchmarkLinks: ["SOXX", "SMH"], tags: ["semis", "equipment", "wafers"] },
  { symbol: "LRCX", name: "Lam Research", tier: "tier2", section: "tech", segment: "equipment", benchmarkLinks: ["SOXX", "SMH"], tags: ["semis", "equipment", "etch"] },
  { symbol: "KLAC", name: "KLA", tier: "tier2", section: "tech", segment: "equipment", benchmarkLinks: ["SOXX", "SMH"], tags: ["semis", "equipment", "inspection"] },
  { symbol: "ASML", name: "ASML Holding", tier: "tier2", section: "tech", segment: "equipment", benchmarkLinks: ["SOXX", "SMH"], tags: ["semis", "equipment", "lithography"] },
  { symbol: "LSCC", name: "Lattice Semiconductor", tier: "tier2", section: "tech", segment: "fabless", benchmarkLinks: ["SOXX", "SMH", "QQQ"], tags: ["semis", "fpga", "edge-compute"] },
  { symbol: "MXL", name: "MaxLinear", tier: "tier3", section: "tech", segment: "networking", benchmarkLinks: ["SOXX", "SMH"], tags: ["semis", "connectivity", "broadband", "fiber"] },
  { symbol: "AAOI", name: "Applied Optoelectronics", tier: "tier3", section: "tech", segment: "networking", benchmarkLinks: ["QQQ"], tags: ["fiber", "optics", "datacenter", "networking"] },
  { symbol: "STM", name: "STMicroelectronics", tier: "tier2", section: "tech", segment: "adjacent", benchmarkLinks: ["SOXX", "SMH"], tags: ["semis", "industrial", "power", "embedded"] },
  { symbol: "WDC", name: "Western Digital", tier: "tier2", section: "tech", segment: "storage", benchmarkLinks: ["QQQ", "SOXX"], tags: ["storage", "memory", "datacenter"] },
  { symbol: "STX", name: "Seagate Technology", tier: "tier2", section: "tech", segment: "storage", benchmarkLinks: ["QQQ"], tags: ["storage", "datacenter", "drives"] },
  { symbol: "SNDK", name: "Sandisk", tier: "tier2", section: "tech", segment: "storage", benchmarkLinks: ["QQQ", "SOXX"], tags: ["storage", "flash", "memory"] },
  { symbol: "PSTG", name: "Pure Storage", tier: "tier2", section: "tech", segment: "storage", benchmarkLinks: ["QQQ"], tags: ["storage", "flash", "datacenter", "enterprise"] },
  { symbol: "CRDO", name: "Credo Technology", tier: "tier2", section: "tech", segment: "datacenter", benchmarkLinks: ["SOXX", "SMH"], tags: ["connectivity", "datacenter", "networking"] },
  { symbol: "NBIS", name: "Nebius Group", tier: "tier2", section: "tech", segment: "datacenter", benchmarkLinks: ["QQQ"], tags: ["cloud", "gpu", "ai-infra"] },
  { symbol: "DELL", name: "Dell Technologies", tier: "tier2", section: "tech", segment: "datacenter", benchmarkLinks: ["QQQ"], tags: ["servers", "hardware", "datacenter"] },
  { symbol: "HPE", name: "Hewlett Packard Enterprise", tier: "tier2", section: "tech", segment: "datacenter", benchmarkLinks: ["QQQ"], tags: ["servers", "networking", "enterprise"] },
  { symbol: "EQIX", name: "Equinix", tier: "tier2", section: "tech", segment: "datacenter", benchmarkLinks: ["QQQ"], tags: ["datacenter", "internet-infrastructure", "colo"] },
  { symbol: "DLR", name: "Digital Realty Trust", tier: "tier2", section: "tech", segment: "datacenter", benchmarkLinks: ["QQQ"], tags: ["datacenter", "internet-infrastructure", "colo"] },
  { symbol: "CORZ", name: "Core Scientific", tier: "tier3", section: "tech", segment: "datacenter", benchmarkLinks: ["QQQ"], tags: ["mining", "compute", "datacenter", "bitcoin"] },
  { symbol: "IREN", name: "Iris Energy", tier: "tier3", section: "tech", segment: "datacenter", benchmarkLinks: ["QQQ"], tags: ["mining", "compute", "datacenter", "bitcoin"] },
  { symbol: "MARA", name: "MARA Holdings", tier: "tier3", section: "tech", segment: "datacenter", benchmarkLinks: ["QQQ"], tags: ["mining", "compute", "bitcoin", "infrastructure"] },
  { symbol: "RIOT", name: "Riot Platforms", tier: "tier3", section: "tech", segment: "datacenter", benchmarkLinks: ["QQQ"], tags: ["mining", "compute", "bitcoin", "infrastructure"] },
  { symbol: "VST", name: "Vistra", tier: "tier2", section: "tech", segment: "power", benchmarkLinks: ["QQQ"], tags: ["power", "datacenter", "electricity"] },
  { symbol: "NEE", name: "NextEra Energy", tier: "tier2", section: "tech", segment: "power", benchmarkLinks: ["QQQ"], tags: ["power", "grid", "utilities", "infrastructure"] },
  { symbol: "OKLO", name: "Oklo", tier: "tier3", section: "tech", segment: "power", benchmarkLinks: ["QQQ"], tags: ["nuclear", "power", "datacenter"] },
  { symbol: "CEG", name: "Constellation Energy", tier: "tier2", section: "tech", segment: "power", benchmarkLinks: ["QQQ"], tags: ["power", "nuclear", "grid"] },
  { symbol: "GEV", name: "GE Vernova", tier: "tier2", section: "tech", segment: "power", benchmarkLinks: ["QQQ"], tags: ["grid", "power", "infrastructure"] },
  { symbol: "SLDP", name: "Solid Power", tier: "tier3", section: "tech", segment: "power", benchmarkLinks: ["QQQ"], tags: ["batteries", "power", "materials", "speculative"] },
  { symbol: "ASTS", name: "AST SpaceMobile", tier: "tier3", section: "tech", segment: "space", benchmarkLinks: ["QQQ"], tags: ["space", "satellites", "communications"] },
  { symbol: "RKLB", name: "Rocket Lab", tier: "tier3", section: "tech", segment: "space", benchmarkLinks: ["QQQ"], tags: ["space", "launch", "satellites"] },
  { symbol: "LUNR", name: "Intuitive Machines", tier: "tier3", section: "tech", segment: "space", benchmarkLinks: ["QQQ"], tags: ["space", "moon", "speculative"] },
  { symbol: "RDW", name: "Redwire", tier: "tier3", section: "tech", segment: "space", benchmarkLinks: ["QQQ"], tags: ["space", "manufacturing", "speculative"] },
  { symbol: "PL", name: "Planet Labs", tier: "tier3", section: "tech", segment: "space", benchmarkLinks: ["QQQ"], tags: ["space", "earth-observation", "data"] },
  { symbol: "IONQ", name: "IonQ", tier: "tier3", section: "tech", segment: "quantum", benchmarkLinks: ["QQQ"], tags: ["quantum", "speculative", "compute"] },
  { symbol: "RGTI", name: "Rigetti Computing", tier: "tier3", section: "tech", segment: "quantum", benchmarkLinks: ["QQQ"], tags: ["quantum", "speculative", "compute"] },
  { symbol: "QBTS", name: "D-Wave Quantum", tier: "tier3", section: "tech", segment: "quantum", benchmarkLinks: ["QQQ"], tags: ["quantum", "speculative", "annealing"] },
  { symbol: "QUBT", name: "Quantum Computing", tier: "tier3", section: "tech", segment: "quantum", benchmarkLinks: ["QQQ"], tags: ["quantum", "speculative", "software"] },
  { symbol: "NVTS", name: "Navitas Semiconductor", tier: "tier3", section: "tech", segment: "power", benchmarkLinks: ["SOXX", "SMH"], tags: ["power", "gallium-nitride", "semis"] },
  { symbol: "ON", name: "ON Semiconductor", tier: "tier3", section: "tech", segment: "power", benchmarkLinks: ["SOXX", "SMH"], tags: ["semis", "auto", "power"] },
  { symbol: "NXPI", name: "NXP Semiconductors", tier: "tier3", section: "tech", segment: "adjacent", benchmarkLinks: ["SOXX", "SMH"], tags: ["semis", "auto", "industrial"] },
  { symbol: "MCHP", name: "Microchip Technology", tier: "tier3", section: "tech", segment: "adjacent", benchmarkLinks: ["SOXX", "SMH"], tags: ["semis", "industrial", "embedded"] },
  { symbol: "ADI", name: "Analog Devices", tier: "tier2", section: "tech", segment: "adjacent", benchmarkLinks: ["SOXX", "SMH"], tags: ["analog", "industrial", "liquid-options"] },
  { symbol: "TXN", name: "Texas Instruments", tier: "tier2", section: "tech", segment: "adjacent", benchmarkLinks: ["SOXX", "SMH", "QQQ"], tags: ["analog", "industrial", "liquid-options"] },
  { symbol: "CDNS", name: "Cadence Design Systems", tier: "tier3", section: "tech", segment: "eda", benchmarkLinks: ["QQQ"], tags: ["eda", "design-tools", "adjacent"] },
  { symbol: "SNPS", name: "Synopsys", tier: "tier3", section: "tech", segment: "eda", benchmarkLinks: ["QQQ"], tags: ["eda", "design-tools", "adjacent"] },
  { symbol: "PANW", name: "Palo Alto Networks", tier: "tier2", section: "tech", segment: "software", benchmarkLinks: ["QQQ"], tags: ["cybersecurity", "software", "growth"] },
  { symbol: "CRWD", name: "CrowdStrike", tier: "tier2", section: "tech", segment: "software", benchmarkLinks: ["QQQ"], tags: ["cybersecurity", "software", "growth"] },
  { symbol: "NET", name: "Cloudflare", tier: "tier2", section: "tech", segment: "software", benchmarkLinks: ["QQQ"], tags: ["cloud", "networking", "software"] },
  { symbol: "DDOG", name: "Datadog", tier: "tier2", section: "tech", segment: "software", benchmarkLinks: ["QQQ"], tags: ["software", "cloud", "observability"] },
  { symbol: "CRCL", name: "Circle Internet Group", tier: "tier2", section: "tech", segment: "software", benchmarkLinks: ["QQQ"], tags: ["internet-infrastructure", "payments", "stablecoin", "fintech"] },
  { symbol: "ZS", name: "Zscaler", tier: "tier2", section: "tech", segment: "software", benchmarkLinks: ["QQQ"], tags: ["security", "cloud", "internet-infrastructure"] },
  { symbol: "LMT", name: "Lockheed Martin", tier: "tier1", section: "defense", segment: "adjacent", benchmarkLinks: ["ITA", "SPY"], tags: ["defense", "aviation", "military-contracts", "liquid-options"] },
  { symbol: "RTX", name: "RTX", tier: "tier1", section: "defense", segment: "adjacent", benchmarkLinks: ["ITA", "XAR", "SPY"], tags: ["defense", "aviation", "missiles", "military-contracts", "liquid-options"] },
  { symbol: "NOC", name: "Northrop Grumman", tier: "tier1", section: "defense", segment: "adjacent", benchmarkLinks: ["ITA", "SPY"], tags: ["defense", "space", "military-contracts", "liquid-options"] },
  { symbol: "GD", name: "General Dynamics", tier: "tier1", section: "defense", segment: "adjacent", benchmarkLinks: ["ITA", "SPY"], tags: ["defense", "submarines", "military-contracts", "liquid-options"] },
  { symbol: "BA", name: "Boeing", tier: "tier1", section: "defense", segment: "adjacent", benchmarkLinks: ["ITA", "XAR", "SPY"], tags: ["aviation", "defense", "aerospace", "liquid-options"] },
  { symbol: "LHX", name: "L3Harris Technologies", tier: "tier2", section: "defense", segment: "networking", benchmarkLinks: ["ITA", "SPY"], tags: ["defense", "communications", "electronics", "military-contracts"] },
  { symbol: "HII", name: "Huntington Ingalls Industries", tier: "tier2", section: "defense", segment: "adjacent", benchmarkLinks: ["ITA", "SPY"], tags: ["defense", "shipbuilding", "naval", "military-contracts"] },
  { symbol: "LDOS", name: "Leidos Holdings", tier: "tier2", section: "defense", segment: "software", benchmarkLinks: ["ITA", "SPY"], tags: ["defense", "government-it", "military-contracts", "cyber"] },
  { symbol: "KTOS", name: "Kratos Defense & Security Solutions", tier: "tier3", section: "defense", segment: "software", benchmarkLinks: ["ITA", "XAR"], tags: ["defense", "drones", "military-contracts", "speculative"] },
  { symbol: "AVAV", name: "AeroVironment", tier: "tier2", section: "defense", segment: "adjacent", benchmarkLinks: ["XAR", "ITA"], tags: ["defense", "drones", "military-contracts"] },
  { symbol: "PLTR", name: "Palantir Technologies", tier: "tier1", section: "defense", segment: "software", benchmarkLinks: ["QQQ", "SPY"], tags: ["defense", "government", "software", "data", "liquid-options"] },
  { symbol: "CW", name: "Curtiss-Wright", tier: "tier2", section: "defense", segment: "adjacent", benchmarkLinks: ["ITA", "SPY"], tags: ["defense", "aviation", "industrial", "military-contracts"] },
  { symbol: "TXT", name: "Textron", tier: "tier2", section: "defense", segment: "adjacent", benchmarkLinks: ["ITA", "XAR", "SPY"], tags: ["aviation", "defense", "helicopters", "military-contracts"] },
  { symbol: "HEI", name: "HEICO", tier: "tier2", section: "defense", segment: "adjacent", benchmarkLinks: ["ITA", "SPY"], tags: ["aviation", "aerospace-parts", "defense"] },
  { symbol: "BWXT", name: "BWX Technologies", tier: "tier2", section: "defense", segment: "power", benchmarkLinks: ["ITA", "SPY"], tags: ["defense", "nuclear", "naval", "government-contracts"] },
  { symbol: "XAR", name: "SPDR S&P Aerospace & Defense ETF", tier: "tier1", section: "defense", segment: "index", benchmarkLinks: ["XAR"], tags: ["defense", "aviation", "etf", "sector"] },
  { symbol: "ITA", name: "iShares U.S. Aerospace & Defense ETF", tier: "tier1", section: "defense", segment: "index", benchmarkLinks: ["ITA"], tags: ["defense", "aviation", "etf", "sector", "liquid-options"] },
  { symbol: "AAPL", name: "Apple", tier: "tier1", section: "leaders", segment: "platform", benchmarkLinks: ["QQQ", "SPY", "XLK"], tags: ["mega-cap", "consumer-tech", "liquid-options"] },
  { symbol: "MSFT", name: "Microsoft", tier: "tier1", section: "leaders", segment: "platform", benchmarkLinks: ["QQQ", "SPY", "XLK"], tags: ["mega-cap", "software", "cloud", "liquid-options"] },
  { symbol: "AMZN", name: "Amazon", tier: "tier1", section: "leaders", segment: "platform", benchmarkLinks: ["QQQ", "SPY", "XLY"], tags: ["mega-cap", "cloud", "consumer", "liquid-options"] },
  { symbol: "GOOGL", name: "Alphabet", tier: "tier1", section: "leaders", segment: "platform", benchmarkLinks: ["QQQ", "SPY", "XLC"], tags: ["mega-cap", "internet", "ads", "liquid-options"] },
  { symbol: "META", name: "Meta Platforms", tier: "tier1", section: "leaders", segment: "platform", benchmarkLinks: ["QQQ", "SPY", "XLC"], tags: ["mega-cap", "social", "ads", "liquid-options"] },
  { symbol: "TSLA", name: "Tesla", tier: "tier1", section: "leaders", segment: "platform", benchmarkLinks: ["QQQ", "SPY", "XLY"], tags: ["mega-cap", "ev", "liquid-options"] },
  { symbol: "NFLX", name: "Netflix", tier: "tier1", section: "leaders", segment: "platform", benchmarkLinks: ["QQQ", "SPY", "XLC"], tags: ["mega-cap", "streaming", "liquid-options"] },
  { symbol: "SPY", name: "SPDR S&P 500 ETF Trust", tier: "tier1", section: "leaders", segment: "index", benchmarkLinks: ["SPY"], tags: ["index", "etf", "market", "liquid-options"] },
  { symbol: "QQQ", name: "Invesco QQQ Trust", tier: "tier1", section: "leaders", segment: "index", benchmarkLinks: ["QQQ"], tags: ["index", "etf", "nasdaq", "liquid-options"] },
  { symbol: "IWM", name: "iShares Russell 2000 ETF", tier: "tier1", section: "leaders", segment: "index", benchmarkLinks: ["IWM"], tags: ["index", "etf", "small-cap", "liquid-options"] },
  { symbol: "DIA", name: "SPDR Dow Jones Industrial Average ETF Trust", tier: "tier1", section: "leaders", segment: "index", benchmarkLinks: ["DIA"], tags: ["index", "etf", "dow", "liquid-options"] },
  { symbol: "XLK", name: "Technology Select Sector SPDR Fund", tier: "tier1", section: "leaders", segment: "index", benchmarkLinks: ["XLK"], tags: ["index", "etf", "tech", "liquid-options"] },
  { symbol: "XLC", name: "Communication Services Select Sector SPDR Fund", tier: "tier1", section: "leaders", segment: "index", benchmarkLinks: ["XLC"], tags: ["index", "etf", "communications", "liquid-options"] },
  { symbol: "XLY", name: "Consumer Discretionary Select Sector SPDR Fund", tier: "tier1", section: "leaders", segment: "index", benchmarkLinks: ["XLY"], tags: ["index", "etf", "consumer", "liquid-options"] },
  { symbol: "SOXX", name: "iShares Semiconductor ETF", tier: "tier1", section: "leaders", segment: "index", benchmarkLinks: ["SOXX"], tags: ["index", "etf", "semis", "liquid-options"] },
  { symbol: "SMH", name: "VanEck Semiconductor ETF", tier: "tier1", section: "leaders", segment: "index", benchmarkLinks: ["SMH"], tags: ["index", "etf", "semis", "liquid-options"] },
  { symbol: "IGV", name: "iShares Expanded Tech-Software Sector ETF", tier: "tier1", section: "leaders", segment: "index", benchmarkLinks: ["IGV"], tags: ["index", "etf", "software", "liquid-options"] },
];
